language: ruby
services:
- postgresql
before_script:
- psql -c 'create database pgapp_test;' -U postgres
before_install:
- sudo apt-get install -y postgresql-server-dev-9.2
script:
- bin/rails db:create
- bin/rails db:migrate
- bundle exec rspec spec
after_script:
- bundle exec rake coveralls:push
notifications: 
email: false
deploy:
  secure: h1H+xvcS61d7KWUGv6tYqCguU8HSc9dm1o4zQinnZ3kFCCN6GSrhpBRe9LXiYTvndUMw4zPxAqxVM8p5vv5q1sp3h5xslbQdfBisjLygjv7OA2hutIhQuicR0fIVX5BRi9QtEgkj/vo06qAPxywJfyzgZyO3s7ZQE8M7pdtLkLIHr9sD0rrI0GwWT4lXWEmsupIgTAdZfdGY4F3b4iwdV2ZgsqOZ1E56PPU/Zp7M0hi9060zg7eFm43JIGP3i1vi3mmUE7bOa6qR0Ae75fJZSAx+wzgOhXe0mjmWV+0AVT99dI9+uXwzcJcqnAwXOaGglGdsxVyzu/OF/TEsN/RGUBAlQP+xKluCjVW7KWTEhwD9wvwlRGrU0OZeOS2DOyXnwmWtff3VFinFmaId/TlQLtoN8LnD7oXaXVrUuAcmTfZzk+g7NrRsCOzT/Wx0TClb82mZNa1r0V89f/GRXp7E4ClPzVoabbo/9zMpnV73f2kNy6TSAmP7udoULNtGbUlkKspIe+woh1bgizu9SyQPMxa3mwlRIeWFzloI/JjZ+ANWdGhBAX1doO70jAG/VvyV+Al9VCJjoCig88+AFPkra7hSlM2oy1iW+j2hyXI/0XD03R/CKXQRN+DMWq5H81M1TvbviwRTMLF5LRMpRNcJyhuIPROY+aVfcQV6WbSkLCQ=
