language: ruby

services:
- postgresql 

before_script:
- psql -c 'create database' "pgapp_test"; -U postgres || true

before_install:
- sudo apt-get install -y postgresql-server-dev-9.2

notifications:
email: false